version: "3.9"

services:
  dcap-server:
    # include comments for all ther other properties
    volumes:
      - ../gsd/:/var/www/gsd
    environment:
      GSD: ${GSD_DOMAIN}

  gsd_app:
    container_name: gsd-api-app
    image: "bitnami/php-fpm"
    restart: unless-stopped
    volumes:
      - ../gsd/php:/app
    networks:
      - dcap-tier

  dcap-db:
    image: mysql:latest
    container_name: dcap-db
    platform: linux/amd64
    restart: always
    volumes:
      - ../gsd/docker/mysql/init.sql:/data/application/init.sql
    command:
      --init-file /data/application/init.sql
